class Worksheet {
  final String id;
  final String title;
  final String goal;
  final int estimatedMinutes;
  final String content;
  final List<String> steps;

  Worksheet({
    required this.id,
    required this.title,
    required this.goal,
    required this.estimatedMinutes,
    required this.content,
    required this.steps,
  });

  static List<Worksheet> getWorksheets() {
    return [
      Worksheet(
        id: 'WS01',
        title: 'Understanding Sensors',
        goal: 'Learn about the different sensor types and their functions',
        estimatedMinutes: 30,
        content: 'Understanding the optical, inductive, and capacitive sensors used in the Smart Factory system.',
        steps: [
          'Navigate to the I/O screen',
          'Identify the First Gate sensor (optical)',
          'Observe the Inductive sensor - detects ferrous metals (steel)',
          'Study the Capacitive sensor - detects non-ferrous metals (aluminium)',
          'Examine the Photo Gate sensor for position detection',
          'Test each sensor in simulation mode',
          'Record how each sensor responds to different materials',
        ],
      ),
      Worksheet(
        id: 'WS02',
        title: 'Reject Mechanisms',
        goal: 'Understand how defects are detected and rejected',
        estimatedMinutes: 25,
        content: 'Learn about the reject detection logic and rejection mechanisms.',
        steps: [
          'Review reject criteria in the system',
          'Start a production run and monitor rejects',
          'Observe when items are marked as rejects',
          'Study the reject paddle actuation',
          'Analyze reject counters on Run screen',
          'Inject faults to create rejects',
          'Review reject rate in Analytics',
        ],
      ),
      Worksheet(
        id: 'WS03',
        title: 'Understanding the Conveyor',
        goal: 'Master conveyor speed control and operation',
        estimatedMinutes: 25,
        content: 'Learn how to control and optimize the conveyor system.',
        steps: [
          'Go to the Run screen',
          'Study the conveyor speed control slider',
          'Adjust speed from 0% to 100%',
          'Start the system and observe material flow',
          'Test different speed settings',
          'Monitor throughput at different speeds',
          'Practice stopping and starting safely',
        ],
      ),
      Worksheet(
        id: 'WS04',
        title: 'Sorting Counters',
        goal: 'Learn to track and analyze material sorting counts',
        estimatedMinutes: 30,
        content: 'Understanding how materials are counted and tracked during sorting.',
        steps: [
          'Start a sorting run on Run screen',
          'Monitor the Steel counter as ferrous items pass',
          'Observe the Aluminium counter for non-ferrous items',
          'Track the Plastic counter for non-metallic items',
          'Watch the Rejects counter for defective items',
          'Review the Remaining counter for batch progress',
          'Export data and analyze sorting accuracy',
        ],
      ),
      Worksheet(
        id: 'WS05',
        title: 'Driving the Stepper Motor',
        goal: 'Control the gantry stepper motor for precise positioning',
        estimatedMinutes: 35,
        content: 'Learn to operate the stepper motor for the gantry system.',
        steps: [
          'Go to I/O screen manual controls',
          'Locate the gantry step and direction controls',
          'Test gantry step output (advances one step)',
          'Change direction and observe movement',
          'Monitor the Gantry Home sensor',
          'Practice homing the gantry',
          'Understand step counting for positioning',
        ],
      ),
      Worksheet(
        id: 'WS06',
        title: 'Understanding the Plunger',
        goal: 'Learn plunger operation and safety interlocks',
        estimatedMinutes: 20,
        content: 'Understanding the pneumatic plunger and its safety features.',
        steps: [
          'Study the plunger down output in I/O screen',
          'Try to activate plunger while conveyor runs',
          'Observe the safety interlock message',
          'Stop the conveyor completely',
          'Test plunger in manual jog mode',
          'Understand the safety logic',
          'Practice safe plunger operation',
        ],
      ),
      Worksheet(
        id: 'WS07',
        title: 'Delivering Counters',
        goal: 'Monitor and optimize material delivery and throughput',
        estimatedMinutes: 25,
        content: 'Learn to track delivery rates and optimize system performance.',
        steps: [
          'Start production with a batch target',
          'Monitor delivered items in real-time',
          'Check throughput metric (items/minute)',
          'Adjust speed to optimize delivery rate',
          'Track remaining items to delivery',
          'Calculate actual vs target delivery time',
          'Review delivery efficiency in Analytics',
        ],
      ),
      Worksheet(
        id: 'WS08',
        title: 'Robot Arm',
        goal: 'Operate the pneumatic pick-and-place robot arm',
        estimatedMinutes: 30,
        content: 'Learn about the pneumatic robot arm system and vacuum gripper.',
        steps: [
          'Study the vacuum gripper output in I/O',
          'Understand the plunger down function',
          'Review the gantry positioning system',
          'Test vacuum activation in manual mode',
          'Practice pick operation sequence',
          'Practice place operation sequence',
          'Complete a full pick-and-place cycle',
        ],
      ),
      Worksheet(
        id: 'WS09',
        title: 'Commissioning the Cell',
        goal: 'Complete initial setup and commissioning of the Smart Factory',
        estimatedMinutes: 45,
        content: 'Step-by-step commissioning procedure for the complete system.',
        steps: [
          'Verify all sensor connections in I/O screen',
          'Test each output individually',
          'Check safety interlocks are functioning',
          'Configure conveyor speed settings',
          'Set up sorting recipes',
          'Run initial test batch',
          'Verify all counters are working',
          'Document baseline performance metrics',
        ],
      ),
      Worksheet(
        id: 'WS10',
        title: 'Completing the Smart Factory',
        goal: 'Run a complete production cycle from start to finish',
        estimatedMinutes: 40,
        content: 'Execute a full production run with all systems operational.',
        steps: [
          'Set batch target to 100 items',
          'Choose the sorting recipe',
          'Configure optimal conveyor speed',
          'Start production run',
          'Monitor all sensors and outputs',
          'Track progress through all counters',
          'Handle any faults that occur',
          'Review final batch metrics',
          'Generate production report',
        ],
      ),
      Worksheet(
        id: 'WS11',
        title: 'Defects & Reset Sequence',
        goal: 'Learn to handle defects and properly reset the system',
        estimatedMinutes: 25,
        content: 'Understanding defect handling and system reset procedures.',
        steps: [
          'Inject a sensor stuck fault from Settings',
          'Observe defect detection and rejection',
          'Study rising reject rate',
          'Navigate to Home screen',
          'Use Reset Faults button',
          'Verify all faults cleared',
          'Restart production safely',
          'Document the reset sequence',
        ],
      ),
      Worksheet(
        id: 'WS12',
        title: 'Vision System',
        goal: 'Understand vision-based inspection and quality control',
        estimatedMinutes: 30,
        content: 'Learn about vision system concepts for quality inspection.',
        steps: [
          'Study how Photo Gate sensor simulates vision',
          'Understand position detection principles',
          'Learn about image-based defect detection',
          'Review vision system benefits',
          'Practice using sensor data for quality checks',
          'Correlate sensor readings with defects',
          'Plan vision system implementation',
        ],
      ),
      Worksheet(
        id: 'WS13',
        title: 'RFID',
        goal: 'Learn about RFID technology for tracking and identification',
        estimatedMinutes: 20,
        content: 'Understanding RFID concepts in smart manufacturing.',
        steps: [
          'Learn RFID basics and benefits',
          'Understand how RFID tracks materials',
          'Study RFID data in manufacturing',
          'Review RFID integration with PLCs',
          'Explore RFID use cases in Industry 4.0',
          'Plan RFID implementation strategy',
        ],
      ),
      Worksheet(
        id: 'WS14',
        title: 'Network & Communications',
        goal: 'Understand PLC networking and communication protocols',
        estimatedMinutes: 35,
        content: 'Learn about industrial networking and S7 communication.',
        steps: [
          'Go to Settings → PLC Configuration',
          'Study IP address configuration',
          'Understand Rack and Slot settings',
          'Learn about S7 protocol basics',
          'Review connection status monitoring',
          'Study the Data Stream Log',
          'Troubleshoot connection issues',
          'Understand network architecture',
        ],
      ),
      Worksheet(
        id: 'WS15',
        title: 'Data Logging',
        goal: 'Master data collection and logging techniques',
        estimatedMinutes: 30,
        content: 'Learn how to log and manage production data effectively.',
        steps: [
          'Start a production run',
          'Navigate to Analytics screen',
          'Review live metrics being logged',
          'Observe event log entries',
          'Export metrics CSV file',
          'Export event log CSV file',
          'Open files and study data structure',
          'Plan long-term data retention strategy',
        ],
      ),
      Worksheet(
        id: 'WS16',
        title: 'Analytics',
        goal: 'Perform comprehensive data analysis and reporting',
        estimatedMinutes: 40,
        content: 'Master all analytics features for performance optimization.',
        steps: [
          'Review real-time KPI tiles',
          'Analyze throughput trends over time',
          'Study FPY (First Pass Yield) metrics',
          'Examine reject rate patterns',
          'Compare performance across time windows',
          'Calculate OEE manually and verify',
          'Identify optimization opportunities',
          'Create comprehensive performance report',
        ],
      ),
      Worksheet(
        id: 'WS17',
        title: 'IO-Link',
        goal: 'Understand IO-Link smart sensor technology',
        estimatedMinutes: 25,
        content: 'Learn about IO-Link protocol and smart sensor benefits.',
        steps: [
          'Study IO-Link protocol fundamentals',
          'Understand IO-Link vs traditional I/O',
          'Learn about sensor parameterization',
          'Review diagnostic capabilities',
          'Understand process data vs service data',
          'Study IO-Link benefits in Industry 4.0',
          'Plan IO-Link sensor integration',
        ],
      ),
      Worksheet(
        id: 'WS18',
        title: 'Predictive Maintenance',
        goal: 'Use data trends to predict and prevent equipment failures',
        estimatedMinutes: 45,
        content: 'Learn to identify trends indicating maintenance needs.',
        steps: [
          'Run production in normal mode',
          'Enable random faults in Settings',
          'Monitor reject rate trend over time',
          'Identify when performance degrades',
          'Correlate trends with component wear',
          'Set up maintenance thresholds',
          'Plan preventive maintenance schedule',
          'Document predictive indicators',
          'Create maintenance action plan',
        ],
      ),
    ];
  }
}
